# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrjyUyEBSWa_k5YxJAAoZ6Cxg206YodM

# Basic Python Practice Questions.

####1. Check if a year is a leap year.
"""

year = int(input("Enter a year: "))
if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print(year,'is a Leap Year')
else:
    print(year,'is not a Leap Year')

"""####2. Determine if a character is a vowel or consonant"""

ch = input("Enter a single alphabet: ")
if len(ch) == 1 :
    if ch.lower() in ['a','e','i','o','u','A','E','I','O','U']:
        print(ch,'is a Vowel')
    else:
        print(ch,'is a consonant')
else:
    print('Please enter a single alphabet letter')

"""####3. Determine a person's stage of life (child, teen, adult, senior) based on age."""

age = int(input('Enter your age: '))
if age < 0:
    print('Age cannot be negative')
elif age <= 12:
    print('Child')
elif age <= 19:
    print('Teen')
elif age <= 59:
    print('Adult')
else:
    print('Senior')

"""####5. Check if a password meets length criteria (at least 8 characters)."""

password = input('Enter a password: ')
if len(password) >= 8:
    print('Password is valid')
else:
    print('Password is too short')

"""####6. Check if a number is positive, and if so, whether it's even or odd."""

num = int(input("Enter a number: "))
if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive and Odd")
else:
    print("Not Positive")

"""####7. Determine grade based on score: A(>=90), B(>=80), C(>=70), else F."""

score = int(input("Enter score: "))
if score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
else:
    print("F")

"""####8. Determine time of day by hour (0-23):
<6: Early Morning

<12: Morning

<18: Afternoon

<24: Night
"""

hour = int(input("Enter hour (0-23): "))
if hour < 6:
    print("Early Morning")
elif hour < 12:
    print("Morning")
elif hour < 18:
    print("Afternoon")
elif hour < 24:
    print("Night")
else:
    print("Invalid hour")

"""####9. Check if a number is even, check if it is also divisible by 4."""

num = int(input("Enter a number: "))
if num % 2 == 0:
    if num % 4 == 0:
        print("Even and Divisible by 4")
    else:
        print("Even but not Divisible by 4")
else:
    print("Odd")

"""####10. Classify a number by digit count:
Single-digit (|num| < 10)

Two-digit (|num| < 100)

Three or more digits (|num| >= 100)

"""

num = int(input("Enter a number: "))
if abs(num) < 10:
    print("Single-digit")
elif abs(num) < 100:
    print("Two-digit")
else:
    print("Three or more digits")